[build]
  functions = "public/netlify/functions"
  publish = "public"

[functions]
  directory = "public/netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[dev]
  functions = "public/netlify/functions"

[build]
  publish = "public"
  functions = "netlify/functions"
  command = 'sed -i "s/%REACT_APP_FIREBASE_PROJECT_ID%/$REACT_APP_FIREBASE_PROJECT_ID/g" public/contact.html && echo "contact.html injected"'

[build.environment]
  REACT_APP_FIREBASE_PROJECT_ID = "andrew-cares-village-f4cb6"