[build]
  functions = "netlify/functions"
  publish = "public"
  command = 'find public -name "*.html" -exec sed -i "s/%REACT_APP_FIREBASE_PROJECT_ID%/$FIREBASE_PROJECT_ID/g" {} + && sed -i "s/%REACT_APP_FIREBASE_PROJECT_ID%/$FIREBASE_PROJECT_ID/g" public/js/config.js && echo "All files processed with environment variables - $(date)"'

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[dev]
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "FIREBASE_PROJECT_ID,FIREBASE_CLIENT_EMAIL"

